// This file is generated by Sapper — do not edit it!
export const timestamp = 1744759488035;

export const files = [
	"service-worker-index.html",
	"dashboard.gif",
	"error-404-monochrome.svg",
	"favicon.png",
	"global.css",
	"great-success.png",
	"logo-192.png",
	"logo-512.png",
	"manifest.json",
	"sb-admin.css"
];
export { files as assets }; // legacy

export const shell = [
	"client/client.22c28cf0.js",
	"client/BreadcrumbItem.aee96d28.js",
	"client/CardBody.e3424b4c.js",
	"client/CardHeader.bf8c203a.js",
	"client/CardText.d915d773.js",
	"client/index.62e1a94b.js",
	"client/Row.c845cb99.js",
	"client/CardFooter.fe2b5435.js",
	"client/Table.d2faa338.js",
	"client/Image.abba58a5.js",
	"client/AreaChart.fa7068ee.js",
	"client/BarChart.c9dfd08c.js",
	"client/activity_log.e41241a3.js",
	"client/FormGroup.bcb166fc.js",
	"client/settings.e6690849.js",
	"client/static_navigation.11ca5aea.js",
	"client/light_sidenav.663016b9.js",
	"client/charts.e82d572c.js",
	"client/tables.3986ef43.js",
	"client/_layout.f9602395.js",
	"client/login.e73ca87c.js",
	"client/Col.7efe260c.js",
	"client/register.d505970a.js",
	"client/forget_password.06ad88a8.js",
	"client/_layout.d7e0c231.js",
	"client/error_401.7df0b271.js",
	"client/error_404.2084a8f3.js",
	"client/error_500.5cf04674.js",
	"client/_layout.27fa59c2.js",
	"client/index.7ee32ed1.js",
	"client/[slug].209f2ae4.js",
	"client/sapper-dev-client.89e34bae.js",
	"client/client.feff93a2.js"
];

export const routes = [
	{ pattern: /^\/$/ },
	{ pattern: /^\/activity_log\/?$/ },
	{ pattern: /^\/settings\/?$/ },
	{ pattern: /^\/layouts\/static_navigation\/?$/ },
	{ pattern: /^\/layouts\/light_sidenav\/?$/ },
	{ pattern: /^\/charts\/?$/ },
	{ pattern: /^\/tables\/?$/ },
	{ pattern: /^\/pages\/authentication\/forget_password\/?$/ },
	{ pattern: /^\/pages\/authentication\/register\/?$/ },
	{ pattern: /^\/pages\/authentication\/login\/?$/ },
	{ pattern: /^\/pages\/error\/error_401\/?$/ },
	{ pattern: /^\/pages\/error\/error_404\/?$/ },
	{ pattern: /^\/pages\/error\/error_500\/?$/ },
	{ pattern: /^\/blog\/?$/ },
	{ pattern: /^\/blog\/([^\/]+?)\/?$/ }
];